version: "3.3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy:v1
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v1
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v1
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local