version: "3.3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy:v2.1
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v2.1
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v2.1
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local